# Configuration Principale du Site Jekyll

# --- Infos de base et SEO (Amélioré) ---
title: Nebrass Chamakh | Portfolio IA/BI # Titre court pour la barre de navigation
email: chamakhnebrass@gmail.com
description: >-
  Portfolio de Nebrass Chamakh, étudiante en dernière année d'Ingénierie Informatique. 
  Spécialisation en Data Science, LLMs (LangChain, Ollama) et Business Intelligence (Power BI, Talend). 
  Recherche Stage PFE en IA Générative. 
url: "https://nebrass1.github.io" 
baseurl: ""
timezone: Africa/Tunis

# --- Thème et Plugins ---
theme: minima 
plugins:
  - jekyll-feed
  - jekyll-seo-tag # Essentiel pour le SEO

# --- Liens Sociaux et Contacts ---
github_username: Nebrass1
linkedin_username: nebrass-shemakh-470ba7214
mobile_phone: +21629436361 

# --- Paramètres Jekyll ---
markdown: kramdown
highlighter: rouge
permalink: /:title/
exclude: 
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/